use thiserror::Error;

/// Errors generated by the numeric type impls
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    /// Multibase decode error
    #[error(transparent)]
    Multibase(#[from] multibase::Error),

    /// Multitrait decode error
    #[error(transparent)]
    Multtrait(#[from] multitrait::Error),

    /// Multicodec decode error
    #[error(transparent)]
    Multcodec(#[from] multicodec::Error),

    /// Incorrect multicoded sigil
    #[error("Expected {expected:?} sigil but received {received:?} sigil")]
    IncorrectSigil {
        /// The expected codec
        expected: multicodec::prelude::Codec,
        /// The codec deserialized
        received: multicodec::prelude::Codec,
    },
}
